### ISSUE TITLE
Error after upgrading Nodebb to v1.0

### ISSUE THREAD

**Issue by Pilvinen** [NodeBB/nodebb-plugin-composer-redactor#39]
`9/3 11:12 [15788] - error: Error: Cannot find module './plugins'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at Object.<anonymous> (/home/minecraft/mynodebb/node_modules/nodebb-plugin-composer-default/library.js:3:29)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at Object.<anonymous> (/home/minecraft/mynodebb/node_modules/nodebb-plugin-composer-redactor/library.js:5:33)
9/3 11:12 [15788] - warn: [plugins] Unable to parse library for: nodebb-plugin-composer-redactor
`

**Comment by julianlam** [comment]
Should be resolved now.
